# Generated by Django 5.0.6 on 2024-06-25 03:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=tinymce.models.HTMLField(),
        ),
    ]
